include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_init_to_null: ignore
    no_logic_in_create_state: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
