name: medicine_chest
description: "Medicine chest mobile application"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  fluttertoast: ^8.2.8
  table_calendar: ^3.1.2
  http: ^1.2.2
  test: ^1.25.7
  uuid: ^4.5.0
  mobile_scanner: ^5.2.3
  flutter_local_notifications: ^17.2.2
  flutter_timezone: ^3.0.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/